### PR TITLE
Create profile view

### LINKED ISSUE #17: Screen after a User Registers
After a user registers, lead them to a screen to set all the initial information for their profile

### PR DESCRIPTION
**Pull request by GerardoMares**
resolves #17 

* Added a Create Profile VC to ensure that after user logs in or creates account we have necessary profile info, they can't get past this screen until account created

* if the user does have profile then send them to main app screen

* if they dont then get the profile info including image, bio, name, and pet type

* store all the data in firebase

### CODE REVIEW

**Comment by gigarza** [comment]
I'm not sure how to check what is actually happening in the database, but seems to be good. The only thing I noticed is that you can click 'create' without having all the fields filled out on the createProfileVC and it does nothing (doesn't lead to another screen or anything). Would we want an alert to pop-up if a user doesn't fill out specific information? I'm not saying we have to at all just a consideration

**Comment by GerardoMares** [comment]
Yea I'll go ahead and add an alert popup on an error and bad input!

**Review by gigarza — APPROVED** [review]

**Comment by j-palos** [comment]
I can't seem to get to the new login/register screen. 
It kicks me directly to the profile screen as if I'm logged in, and I can't find the logout button? Code wise though it seems okay.

**Comment by GerardoMares** [comment]
Oh yea, it's cause I ended up using the bob123@gmail account to test creating the profile. I'll delete the profile so you can try it and see it. Also, the logout button is in the settings. It won't let you get past the screen without selecting an image but the simulator should have a few images in there to choose from.  @j-palos

**Comment by j-palos** [comment]
> Oh yea, it's cause I ended up using the bob123@gmail account to test creating the profile. I'll delete the profile so you can try it and see it. Also, the logout button is in the settings. It won't let you get past the screen without selecting an image but the simulator should have a few images in there to choose from. @j-palos

looks good. Only complaint is maybe we want that scroll of options for pets to cover the screen totally so they don't think they can type, or we would rather them not type.

**Review by j-palos — APPROVED** [review]

**Pull request merged**
