### PR TITLE
Matches: Upcoming Events; Circle Pictures

### PR DESCRIPTION
**Pull request by gigarza**
- Calendar Screen now done
- Profile Pictures now viewed as circles instead of squares

Left for Matches Screen:
- Switch button at bottom for matches vs calendar
- New Matches (horizontal scroll)

### CODE REVIEW

**Comment by j-palos** [comment]
There's an issue where if you go to the matches screen and then to the calendar, you can no longer get back to the other tabs. I'm not sure if that's something you did or because the navigation i did before isn't complete though. We can look into it later. 

Edit: Sabrina noticed that we're actually leaving the paging view controller's scope when you segue to that calendar VC, so we'll have to do something about that. Maybe make the calendar an embedded view of the matches screen?

As an aside, Sabrina suggested that the upcoming events be a tableview rather than 3 ui views embedded? Just a a thought.

**Comment by gigarza** [comment]
Hmm not sure about the first one? Maybe I don't quite understand what you're saying? The switch at bottom (which I still need to add in) is going to let it go back to all the Matches, and I thought the nav bar on top would lead to the rest of the app? Again, I probably am just not understanding what you are saying.

The reason I didn't do a tableview, and did the 3 UI views, is so that I could have the color space in between each of the selected. I don't mind doing a tableView as that'd be easy to implement.

**Comment by gigarza** [comment]
Maybe you're talking about the Meetup screen? If so, I hadn't implemented the submit button to go back to Matches Screen yet, the nav bar on top, and this screen will also have the matches/calendar switch at the bottom.

**Comment by j-palos** [comment]
Nah I mean the top nav that takes us to matches in the first place, it
should still be there later. But we can't get back to profile or swipe
view.

**Comment by gigarza** [comment]
I guess we can talk about that cause I'm still unsure as to why the nav bar is a problem on that screen, and I'm probably just not understanding the problem

**Pull request merged**
