### PR TITLE
Update profile

### LINKED ISSUE #38: Go back and make the profile screen actually save to the database

### PR DESCRIPTION
**Pull request by GerardoMares**
resolves #38

### CODE REVIEW

**Review by j-palos — COMMENTED** [review]
It looks like there's still the issue of pet types a user is looking for is defaulted to nothing. When I cleared data and logged in as bob123 I initially couldn't find any swipes because pettype was defaulted to nothing.

Not sure if that should be dealt with in this PR

**Comment by GerardoMares** [comment]
Should the default be all pet types?

**Comment by j-palos** [comment]
> Should the default be all pet types?

Either that, or they decide it on account creation?

**Comment by GerardoMares** [comment]
changed it to default to all pet types if using default not set.

**Review by j-palos — APPROVED** [review]

**Pull request merged**
